version: '3.8'

# Define a rede externa e o volume externo
networks:
  network_public:
    external: true
    name: network_public

volumes:
  chatwoot_storage_volume:
    external: true
    name: chatwoot_storage_volume

services:
  # Define uma base para reuso, usando a imagem publicada e env_file
  base: &base
    # USA A IMAGEM PUBLICADA NO DOCKER HUB
    image: nieldk/chatwoot-modificado:latest
    env_file: .env
    # Monta o volume externo para armazenamento persistente
    volumes:
      - chatwoot_storage_volume:/app/storage
    # Conecta à rede externa
    networks:
      - network_public

  # Serviço principal da aplicação Rails
  rails:
    <<: *base
    # container_name e restart removidos (não suportados neste modo de deploy)
    # deploy removido (não suportado neste modo de deploy)
    # Depende dos serviços externos (Postgres e Redis já devem estar rodando)
    ports:
      - '3000:3000' # Expõe a porta 3000 internamente
    environment:
      # Variáveis específicas do Rails (algumas vêm do .env)
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      # Garante que o nome do banco de dados seja o mesmo do seu ambiente
      - POSTGRES_DATABASE=chatwoot
    # CORRIGIDO: Usando caminho absoluto para o entrypoint
    entrypoint: /app/docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  # Serviço Sidekiq para processamento em background
  sidekiq:
    <<: *base
    # container_name e restart removidos (não suportados neste modo de deploy)
    # deploy removido (não suportado neste modo de deploy)
    # Depende do serviço Rails estar iniciado
    depends_on:
      - rails
    environment:
      # Variáveis específicas do Sidekiq (algumas vêm do .env)
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      # Garante que o nome do banco de dados seja o mesmo do seu ambiente
      - POSTGRES_DATABASE=chatwoot
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

# Serviços de Postgres e Redis foram removidos pois você usa versões externas.
# Volumes postgres_data e redis_data foram removidos.
# O volume storage_data foi substituído pelo volume externo chatwoot_storage_volume.

